import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { ScrollView, TouchableOpacity } from 'react-native-gesture-handler';
import { Ionicons } from '@expo/vector-icons';

const LegalTerms = ({ navigation }) => {
  React.useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <TouchableOpacity
          onPress={() => navigation.goBack()}
          style={{
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: 'rgba(21,22,48,0.1)',
            justifyContent: 'center',
            alignItems: 'center',
            marginLeft: 20,
          }}>
          <Ionicons name="ios-arrow-round-back" size={32} color="#fff" />
        </TouchableOpacity>
      ),
    });
  });
  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      <Text style={styles.header}>1. Introduction</Text>
      <Text style={styles.body}>
        Welcome to
        <Text style={{ fontWeight: 'bold', color:"#000a43" }}>{''} Ticket Pouch.</Text>
      </Text>
      <Text style={styles.body}>
        We use your data to provide and improve Service. By using Service, you
        agree to the collection and use of information in accordance with this
        policy. Unless otherwise defined in this Privacy Policy, the terms used
        in this Privacy Policy have the same meanings as in our Terms and
        Conditions. Our Terms and Conditions{' '}
        <Text style={{ fontWeight: 'bold', color:"#000a43" }}>(“Terms”)</Text> govern all use of
        our Service and together with the Privacy Policy constitutes your
        agreement with us{' '}
        <Text style={{ fontWeight: 'bold', color:"#000a43" }}>(“agreement”).</Text>
      </Text>
      <Text style={styles.header}> 2. Definitions</Text>
      <Text style={styles.body}>
        <Text style={{ fontWeight: 'bold', color:"#000a43" }}>PERSONAL DATA</Text> means data
        about a living individual who can be identified from those data (or from
        those and other information either in our possession or likely to come
        into our possession).
      </Text>
      <Text style={styles.body}>
        <Text style={{ fontWeight: 'bold', color:"#000a43" }}>USAGE DATA</Text> is data collected
        automatically either generated by the use of Service or from Service
        infrastructure itself (for example, the duration of a page visit).
      </Text>
      <Text style={styles.body}>
        <Text style={{ fontWeight: 'bold', color:"#000a43" }}>DATA CONTROLLER </Text> means a
        natural or legal person who (either alone or jointly or in common with
        other persons) determines the purposes for which and the manner in which
        any personal data are, or are to be, processed. For the purpose of this
        Privacy Policy, we are a Data Controller of your data.
      </Text>
      <Text style={styles.header}>3. Information Collection and Use</Text>
      <Text style={styles.body}>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </Text>
      <Text style={styles.header}>4. Data Collected</Text>
      <Text style={styles.body}>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information may
        include, but is not limited to:
      </Text>
      <Text style={styles.body}>0.1. Email address</Text>
      <Text style={styles.body}>0.2. First name and last name</Text>
      <Text style={styles.body}>0.3. Phone number</Text>
      <Text style={styles.body}>
        0.4. Address, Country, State, Province, ZIP/Postal code, City
      </Text>
      <Text style={styles.body}>0.5. Cookies and Usage Data</Text>
      <Text style={styles.header}>5. Contact Us</Text>
      <Text style={styles.body}>
        If you have any questions about this Privacy Policy, please contact us
        by email: ticketpouch@gmail.com.
      </Text>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 10,
  },
  header: {
    fontWeight: 'bold',
    fontSize: 21,
    marginBottom: 20,
    color:"#073068",
    fontFamily:'TTCommons-Bold'
  },
  body: {
    fontSize: 18,
    marginBottom: 20,
    textAlign:"justify",
    lineHeight:20,
    fontFamily:'TTCommons-Regular'
  },
});
export default LegalTerms;
